"""Report generator - produces structured analysis reports.

Generates reports in multiple formats (Markdown, JSON, HTML) from
the analysis results using Jinja2 templates.
"""

from __future__ import annotations

from jinja2 import Environment

from test_analysis_agent.models.schemas import AnalysisReport

_MD_TEMPLATE = """# Pipeline Failure Analysis Report

**Job:** {{ report.job_name }} #{{ report.build_number }}
{% if report.build_url %}**URL:** {{ report.build_url }}{% endif %}
**Analyzed at:** {{ report.analyzed_at.strftime('%Y-%m-%d %H:%M:%S UTC') }}
**Overall Status:** {{ report.overall_status }}
**Failure Stage:** {{ report.failure_stage.value }}

---

## Executive Summary

{{ report.summary }}

---

## Pipeline Stages

{% for stage in report.stage_results %}
### {{ stage.stage.value | capitalize }} Stage — {{ stage.status | upper }}
{% if stage.error_summary %}
**Errors:**
```
{{ stage.error_summary }}
```
{% endif %}
{% if stage.triggered_jobs %}
**Triggered Jobs:**
{% for job in stage.triggered_jobs %}
- {{ job.job_name }} #{{ job.build_number }}: {{ job.status }}
{% endfor %}
{% endif %}
{% endfor %}

{% if report.total_tests > 0 %}
---

## Test Results

| Metric | Count |
|--------|-------|
| Total  | {{ report.total_tests }} |
| Passed | {{ report.passed_tests }} |
| Failed | {{ report.failed_tests }} |
| Broken | {{ report.broken_tests }} |
| Skipped | {{ report.skipped_tests }} |

{% if report.test_failures %}
### Failed Test Cases

{% for tc in report.test_failures %}
#### {{ loop.index }}. {{ tc.test_name }}

- **Status:** {{ tc.status }}
- **Class:** {{ tc.test_class or 'N/A' }}
- **Suite:** {{ tc.suite_name or 'N/A' }}
- **Category:** {{ tc.failure_category.value }}
{% if tc.error_message %}
- **Error:** `{{ tc.error_message[:200] }}`
{% endif %}
{% if tc.ai_analysis %}

**AI Analysis:** {{ tc.ai_analysis }}
{% endif %}

{% endfor %}
{% endif %}
{% endif %}

---

## Identified Issues

{% for issue in report.issues %}
### {{ loop.index }}. [{{ issue.severity.value | upper }}] {{ issue.title }}

- **Category:** {{ issue.category.value }}
- **Stage:** {{ issue.stage.value }}
- **Description:** {{ issue.description }}
{% if issue.root_cause %}- **Root Cause:** {{ issue.root_cause }}{% endif %}
{% if issue.suggestion %}- **Suggestion:** {{ issue.suggestion }}{% endif %}
{% if issue.should_file_bug %}- **🐛 Bug Recommended:** {{ issue.bug_summary or 'Yes' }}{% endif %}
{% if issue.affected_tests %}- **Affected Tests:** {{ issue.affected_tests | join(', ') }}{% endif %}

{% endfor %}

{% if report.bug_recommendations %}
---

## Bug Filing Recommendations

{% for rec in report.bug_recommendations %}
### {{ loop.index }}. {{ rec.summary }}
{% if rec.severity %}- **Severity:** {{ rec.severity.value }}{% endif %}
{% if rec.category %}- **Category:** {{ rec.category.value }}{% endif %}
{% if rec.affected_stage %}- **Affected Stage:** {{ rec.affected_stage.value }}{% endif %}
{% if rec.affected_jobs %}- **Affected Jobs:** {{ rec.affected_jobs | join(', ') }}{% endif %}

{{ rec.detail_description }}

{% endfor %}
{% endif %}

---
*Report generated by Test Analysis Agent v{{ version }}*
"""


def generate_markdown_report(report: AnalysisReport, version: str = "0.1.0") -> str:
    """Generate a Markdown format report."""
    env = Environment(autoescape=False)
    template = env.from_string(_MD_TEMPLATE)
    return template.render(report=report, version=version)


def generate_json_report(report: AnalysisReport) -> str:
    """Generate a JSON format report."""
    return report.model_dump_json(indent=2)


def generate_html_report(report: AnalysisReport, version: str = "0.1.0") -> str:
    """Generate a simple HTML report by converting Markdown."""
    md_content = generate_markdown_report(report, version)
    # Simple markdown-to-html conversion for key elements
    html = _simple_md_to_html(md_content)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Pipeline Failure Analysis - {report.job_name} #{report.build_number}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       max-width: 960px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }}
h1 {{ color: #d32f2f; border-bottom: 2px solid #d32f2f; padding-bottom: 10px; }}
h2 {{ color: #1565c0; margin-top: 30px; }}
h3 {{ color: #2e7d32; }}
code {{ background: #f5f5f5; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }}
pre {{ background: #263238; color: #eee; padding: 16px; border-radius: 6px; overflow-x: auto; }}
table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
th, td {{ border: 1px solid #ddd; padding: 8px 12px; text-align: left; }}
th {{ background: #f5f5f5; }}
.critical {{ color: #d32f2f; font-weight: bold; }}
.high {{ color: #e65100; font-weight: bold; }}
.medium {{ color: #f9a825; }}
.low {{ color: #2e7d32; }}
</style>
</head>
<body>
{html}
</body>
</html>"""


def _simple_md_to_html(md: str) -> str:
    """Very basic markdown to HTML conversion."""
    import re

    lines = md.split("\n")
    html_lines: list[str] = []
    in_code_block = False
    in_table = False

    for line in lines:
        if line.strip().startswith("```"):
            if in_code_block:
                html_lines.append("</code></pre>")
                in_code_block = False
            else:
                html_lines.append("<pre><code>")
                in_code_block = True
            continue

        if in_code_block:
            html_lines.append(line)
            continue

        # Table handling
        if "|" in line and not line.strip().startswith("#"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if all(c.replace("-", "").replace(":", "") == "" for c in cells):
                continue  # Skip separator row
            if not in_table:
                html_lines.append("<table>")
                in_table = True
            tag = "th" if not in_table or html_lines[-1] == "<table>" else "td"
            row = "".join(f"<{tag}>{c}</{tag}>" for c in cells)
            html_lines.append(f"<tr>{row}</tr>")
            continue
        elif in_table:
            html_lines.append("</table>")
            in_table = False

        # Headers
        if line.startswith("####"):
            html_lines.append(f"<h4>{line[5:].strip()}</h4>")
        elif line.startswith("###"):
            html_lines.append(f"<h3>{line[4:].strip()}</h3>")
        elif line.startswith("##"):
            html_lines.append(f"<h2>{line[3:].strip()}</h2>")
        elif line.startswith("#"):
            html_lines.append(f"<h1>{line[2:].strip()}</h1>")
        elif line.startswith("---"):
            html_lines.append("<hr>")
        elif line.startswith("- "):
            html_lines.append(f"<li>{line[2:]}</li>")
        elif line.strip().startswith("**") and line.strip().endswith("**"):
            html_lines.append(f"<p><strong>{line.strip()[2:-2]}</strong></p>")
        elif line.strip():
            # Inline code
            processed = re.sub(r"`([^`]+)`", r"<code>\1</code>", line)
            # Bold
            processed = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", processed)
            html_lines.append(f"<p>{processed}</p>")
        else:
            html_lines.append("")

    if in_table:
        html_lines.append("</table>")

    return "\n".join(html_lines)
